In [5]:
import pandas as pd
import os
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
import warnings
warnings.simplefilter('ignore')

,Area_Type,Possession_Status,Floors,new_or_resale,furnishing,society,bathrooms,advertiser_name,bhk,price,parking,comments,location,date_of_posting,facing,overlooking,area
0,carpet area,Possession by Mar '22,NaN,New Property,Semi-Furnished,Nahar Olivia,2.0,Amey Sawant,2 BHK Flat,₹ 1.67 Cr,1 Covered,"Olivia is a part of Nahar's Amrit Shakti, an a...","['Nahar Olivia,', 'in Chandivali']","Jan 30, '21",NaN,NaN,653 sqft
1,carpet area,Ready to Move,NaN,New Property,Unfurnished,Ekta Parksville,2.0,Ekta World,2 BHK Flat,₹ 50.7 Lac,1 Covered,"Ekta Parksville, is a 15-storey high-rise luxu...","['Ekta Parksville,', 'in Virar West']","Jan 30, '21",NaN,NaN,583 sqft
2,carpet area,Possession by Jun '24,19 out of 23 floors,New Property,Unfurnished,GS 47th Avenue,2.0,GS GROUP,2 BHK Flat,₹ 1.03 Cr,NaN,"GS 47TH AVENUE in VIKHROLI EAST, Central Mumba...","['GS 47th Avenue,', 'in Vikhroli East']","Jan 28, '21",NaN,NaN,545 sqft
3,carpet area,Possession by Dec '23,NaN,New Property,Unfurnished,Bachraj Lifespace,1.0,Bachraj Developers,2 BHK Flat,₹ 52 Lac,NaN,"Welcome to Bachraj Lifespace, a modern-day lux...","['Bachraj Lifespace,', 'in Virar West']","Jan 30, '21",NaN,NaN,568 sqft
4,carpet area,Possession by Jun '21,1 out of 42 floors,New Property,Unfurnished,Northern Heights,2.0,N Rose Developers Pvt Ltd,2 BHK Flat,₹ 1.50 Cr,1 Covered,Well designed with a keen eye on aesthetics an...,"['Northern Heights,', 'in Dahisar East']","Jan 28, '21",NaN,NaN,656 sqft